import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/context/AuthContext';
import { UserAvatar } from '@/components/ui/UserAvatar';
import { fullName, formatDateTime } from '@/lib/format';
import type { Discussion } from '@/types';

export function QuestionReplies({questionId,cohortId}:{questionId:string;cohortId:string}){
 const {user,roles}=useAuth();const [open,setOpen]=useState(false);const [rows,setRows]=useState<Discussion[]>([]);const [body,setBody]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!open)return;let alive=true;void supabase.from('discussions').select('*,author:profiles(*)').eq('parent_id',questionId).eq('cohort_id',cohortId).order('created_at').then(({data,error})=>{if(!alive)return;if(error)setError(error.message);else setRows(data??[]);});return()=>{alive=false;};},[open,questionId,cohortId]);
 const reply=async()=>{if(!user||!body.trim())return;setSaving(true);setError('');const enrolment=await supabase.from('enrolments').select('id').eq('cohort_id',cohortId).eq('student_id',user.id).eq('status','active').maybeSingle();if(!enrolment.data&&!roles.some(r=>["instructor","administrator"].includes(r))){setError('You must be registered in this cohort to reply.');setSaving(false);return;}const result=await supabase.from('discussions').insert({cohort_id:cohortId,parent_id:questionId,author_id:user.id,title:'Reply',body:body.trim(),is_question:true}).select('*,author:profiles(*)').single();if(result.error)setError(result.error.message);else{setRows(current=>[...current,result.data]);setBody('');}setSaving(false);};
 return <div className="mt-4 border-t border-ink-100 pt-3"><button className="text-sm font-semibold text-brand-700" type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?'Hide conversation':'View conversation / reply'}</button>{open&&<div className="mt-3 space-y-3">{rows.length===0&&<p className="text-sm text-ink-600">No replies yet. Your teaching team can respond here.</p>}{rows.map(row=><article key={row.id} className="rounded-xl bg-brand-50/60 p-3"><div className="flex items-center gap-2 text-xs text-ink-600"><UserAvatar profile={row.author} size="xs" decorative/>{fullName(row.author)} · {formatDateTime(row.created_at)}</div><p className="mt-2 whitespace-pre-wrap text-sm">{row.body}</p></article>)}<label className="block text-sm font-medium" htmlFor={`reply-${questionId}`}>Your reply</label><textarea id={`reply-${questionId}`} className="input min-h-24" maxLength={5000} value={body} onChange={e=>setBody(e.target.value)}/>{error&&<p role="alert" className="text-sm text-danger-700">{error}</p>}<button type="button" className="btn-primary" disabled={saving||!body.trim()} onClick={()=>void reply()}>{saving?'Sending…':'Send reply'}</button></div>}</div>;
}
