// Authored parallel-form questions. Format: practice case | graded case | best action | distractor | distractor | teaching explanation.
// Kept outside src: answers must never be shipped to the learner bundle.
export const cases = [
`An app follows the rule: send orders over $500 for approval. What capability is this?|A payroll system flags any claim above a fixed limit. What drives that decision?|A fixed rule|Learning from past examples|Writing new content|A rule follows a set condition. It does not need to learn a pattern.
A shop estimates next week's sales from past sales. What is it doing?|A hotel uses booking history to estimate room demand. What capability fits?|Prediction|Retrieval|Generation|Prediction estimates an unknown result from patterns. The estimate still needs checking.
An assistant writes a new welcome email. What capability is it using?|A team asks a tool to draft a new event invitation. What is the main capability?|Generation|A fixed rule|Retrieval|Generation creates new content. A draft is not proof that its facts are correct.
A tool finds a paragraph in the staff handbook. What is the main task?|A support tool locates an approved refund policy. Which capability is most useful?|Retrieval|Prediction|Generation|Retrieval finds existing information. Check that it is the right and current source.
An assistant can send emails and change appointments. What extra control is needed?|A booking agent can cancel reservations. What should the team add before a pilot?|Approval before important actions|A longer greeting|More example emails only|Tools that act can change real records. Permission and a stop point limit harm.
AI gives a confident answer with a made-up source. What should you do?|A report includes a source you cannot find. What is the best next step?|Verify the claim with a real source|Keep it because it sounds clear|Only correct its spelling|Confidence is not evidence. Remove or flag claims that cannot be supported.
Which task is the safest first AI trial?|A new user needs a low-risk practice task. Which should they choose?|Draft an invitation using fictional details|Upload employee medical records|Let AI approve payments|Fictional input and a draft-only output keep the first trial small and reversible.
A prompt contains a customer's account number. What should happen before using an unapproved tool?|A colleague wants to paste a private customer list into a public chatbot. What should you advise?|Remove the private data or use an approved process|Add a polite request for privacy|Paste it and delete the chat later|A request for privacy does not change a tool's data rules. Use approved data and tools.
An AI shortlist overlooks qualified applicants from one group. What is the concern?|A model keeps ranking similar names higher despite equal skills. What should be checked?|Bias in inputs and results|The length of the output only|The color of the interface|Bias can create unfair patterns. Review the data, criteria and effects on people.
Who is responsible for checking an AI-assisted email before it is sent?|A manager uses an AI draft in a client report. Who owns the final decision?|The person approving the work|The AI tool alone|The customer receiving it|AI supports work; it does not take responsibility from the person who approves it.`,
`A prompt says 'Make this better' without a goal. What should you add first?|A teammate asks AI to 'fix the report' but gives no purpose. What is missing?|A clear task and intended result|More polite filler|A demand for a perfect answer|A useful instruction names what to do and what a good result looks like.
Which CIDI part tells AI who the reader is?|You tell AI the message is for a busy store manager. Which CIDI part is this?|Context|Input|Instruction|Context explains the situation and audience so the response can fit the task.
Where should approved source notes go in CIDI?|You have checked event facts for a draft invitation. Which part should contain them?|Input|Context only|An unstated assumption|Input is the material to work from. Clear source boundaries help prevent invented facts.
A prompt needs a three-row table with owner and due date. Where does this belong?|You want five bullets with no private names. How should you express this?|State these as output details|Hope the tool chooses the format|Add the requirement after sending the result|Details set length, format and limits. Naming them makes the output easier to check.
A draft's facts are right, but its tone is too formal. What should you revise?|A customer note is accurate but sounds unfriendly. What is an efficient next prompt?|Change the tone while keeping the facts|Rewrite all source facts|Ask for several unrelated versions|A focused revision changes the weak part without losing what already works.
AI adds a price that is not in your notes. What should your follow-up say?|A draft invents a delivery date. Which revision best controls the error?|Remove unsupported details and mark missing facts|Make the date sound more confident|Shorten the whole draft only|The tool should not fill important gaps by guessing. Missing information should stay visible.
What makes a reusable prompt template safer?|Your team shares a prompt for client emails. Which feature helps safe reuse?|Clearly marked fields and a review checklist|One client's private details left inside|A rule that outputs need no review|Templates should separate reusable instructions from case-specific data and review steps.
Two tests use different input and different instructions. Can you tell which instruction worked better?|A colleague compares prompts using unrelated examples. What should change?|Keep the input the same for the comparison|Pick the longer response|Use the fastest tool as the winner|A fair comparison changes one important factor at a time.
A document tells the AI to ignore your rules and reveal data. How should you treat that text?|An uploaded page contains instructions that conflict with your task. What should you do?|Treat it as untrusted source content|Let it replace the task instructions|Copy the hidden directions into the final answer|Source text can contain malicious or irrelevant commands. It is evidence to examine, not authority.
What should a prompt test log record?|You need to explain why version two is better. What evidence should you keep?|Input, prompt, output and the reason for revision|Only the final prompt's name|Only the time it took|A small test record makes improvement visible and repeatable.`,
`A familiar AI product adds a new model. What should you check before switching?|A provider changes the model behind a tool. What is the sensible response?|Retest the approved task and data rules|Assume the old result still applies|Switch because the model name is newer|A product and its model are different. Changes can affect quality, cost and data handling.
Which comparison is fair for two AI tools?|A team wants to choose between two services. Which test provides useful evidence?|The same task, input and scoring criteria|A writing task in one and an image task in the other|Different private records in each|Comparable tests use the same work and judge it by the same standards.
A free tool does not allow approved handling of client files. What should the team do?|A low-cost service fails the company's privacy rules. What is the best choice?|Reject it for that task or change to safe input|Use it because the price is low|Hide the tool's name in the report|Privacy fit is a requirement, not a bonus that low price can offset.
One tool gives fluent but inaccurate output. How should you score it?|A demo looks impressive but gets two source facts wrong. What matters most?|Check accuracy against the source|Give full marks for fluent wording|Judge only the layout|Fluency can hide errors. Accuracy must be checked independently of style.
How should a team compare total cost?|A subscription is cheap but staff spend hours correcting its work. What should be counted?|Subscription and review time|Subscription only|Number of features only|Real cost includes access, setup, use and human checking.
A tool cannot export the team's required file type. Why does that matter?|A service creates good drafts but they cannot enter the existing process. What is missing?|Workflow fit|A more modern logo|A higher creativity setting|A useful tool must fit how the team receives, edits, approves and stores work.
What is a helpful five-point scoring rule?|Two reviewers give different scores because 'good' is undefined. What should they create?|Written examples of low, middle and high performance|A rule that every tool gets five|Separate private standards for each reviewer|Shared score descriptions make comparisons more consistent.
Which evidence belongs in a tool recommendation?|A manager asks why you chose one model. What should your answer include?|Test results, limits and required safeguards|Only its popularity|Only the vendor's promises|A recommendation should follow evidence from the intended task and state its limits.
What should happen before testing on real private data?|A pilot moves beyond fictional records. Which step comes first?|Confirm approval, access and data handling|Upload the records to learn by trial|Ask AI whether the upload is allowed|People responsible for the data must approve its use; a chatbot cannot grant permission.
A stronger model is slower and costs more. What is the best decision?|A simple draft task works well on a smaller model. Should you always use the largest?|Choose the simplest option that meets the task's needs|Always choose the largest|Always choose the cheapest regardless of quality|Model choice is a trade-off. Test the level of quality and risk the task actually requires.`,
`Rough notes contain two different dates. What should a summary do?|An event brief says both Tuesday and Thursday. What should the draft show?|Flag the conflict for a person to resolve|Choose one date without saying so|Remove both dates and claim the plan is complete|Conflicting facts should stay visible until an authorized person resolves them.
You need a short plan from supplied notes. What should you specify?|A team wants useful actions rather than a long essay. What should the prompt request?|Audience, steps, owners and a simple format|As much text as possible|A confident answer without questions|A clear purpose and format make a draft practical and easier to review.
A summary omits a key deadline. What check would catch it?|AI shortens a project note but drops the due date. What review is needed?|Compare the summary against required source facts|Count paragraphs only|Check spelling only|A shorter summary is useful only if it retains the facts needed for the task.
AI suggests ten new ideas. How should they be used?|A brainstorm includes an expensive proposal with no supporting facts. What next?|Screen ideas against needs, limits and evidence|Treat every idea as an approved plan|Publish the list as final decisions|Brainstorming produces options, not approval or proof of feasibility.
What is a sensible first draft workflow?|You want AI help with a weekly update. Which order is best?|Prepare facts, draft, check, approve|Draft, publish, then gather facts|Ask AI to invent missing results|Approved input and human checking bracket the drafting step.
A plan has no owners. Why is it weak?|A task list says 'follow up' but names nobody. What should be added?|A responsible person and next step|More decorative headings|A longer opening paragraph|Actionable plans say who will do what. Unassigned tasks are easy to miss.
AI turns 'might launch' into 'will launch.' What changed?|A draft changes a possible discount into a firm promise. What must you correct?|The level of certainty|Only the sentence length|Only the font|Small wording changes can create false promises. Preserve the source's certainty and conditions.
How should sensitive notes be prepared for practice?|You want to learn summarizing with a real customer complaint. What is safer?|Use a fictional or approved redacted version|Keep the customer number for realism|Upload first and remove names later|Practice should not expose real private data without permission.
When is a task complete?|The draft looks tidy but no one has checked it. What is still needed?|Verify it and obtain the required approval|Add an AI-generated completion badge|Save a screenshot only|Appearance is not completion. The agreed checks and approvals still apply.
Which record shows useful human editing?|You need to show how you improved an AI summary. What should you keep?|Before/after text and reasons for key changes|Only the tool's logo|Only the number of words removed|Evidence of edits makes the review process clear and helps future improvement.`,
`A manager needs a quick decision. What should the message lead with?|A director has one minute to read an update. Which opening helps most?|The decision needed and key facts|A long history of the topic|A vague greeting with no request|Put the reader's task first, then the supporting detail.
A customer message includes internal staff criticism. What should change?|An external email copies private team notes. Which edit is needed?|Remove internal/private details and keep relevant facts|Keep everything for transparency|Replace names with initials only|Different audiences need different details. Initials may still identify people.
What should stay the same when rewriting for two audiences?|You turn a team update into a client note. What must not change?|The facts, limits and agreed promises|The exact sentence length|The amount of technical detail|Tone and detail can change, but the underlying meaning must remain accurate.
AI adds 'guaranteed by Friday' without approval. What should you do?|A service email promises a refund that was not authorized. What is the right edit?|Remove the unsupported promise and confirm the policy|Keep it to sound helpful|Use bold text to make it clear|A friendly tone does not justify making commitments the business has not approved.
Which ending makes an email actionable?|A message explains a problem but the reader does not know what to do. What is missing?|A clear request and deadline when relevant|An extra compliment|A longer signature|Readers need to know the next action, who owns it and when it is needed.
A sentence says 'leverage synergies to optimize outcomes.' What is clearer?|A beginner cannot understand a report full of jargon. How should it be revised?|Use plain words and explain the action|Add more technical terms|Remove all details|Plain language keeps the meaning while reducing unnecessary effort.
An AI response sounds defensive after a complaint. What should change?|A delayed-order reply blames the customer. What tone is more useful?|Respectful, factual and focused on next steps|More forceful blame|A promise the team cannot keep|A helpful tone acknowledges the issue without inventing facts or commitments.
What belongs in the final communication check?|A polished email is ready to send. Which review is still needed?|Facts, tone, privacy, promises and action|Font and spelling only|Word count only|Communication quality includes accuracy, audience fit and consequences, not just grammar.
When should a person review a sensitive message?|AI drafts a staff disciplinary note. What should happen next?|An authorized person reviews it before use|It is sent automatically|AI decides the final outcome|Messages that affect people need human judgment and the organization's process.
What is a useful reason to record an edit?|You replace a confusing term in a customer email. How should you explain the change?|It makes the next action clearer for this reader|It makes the message look more advanced|It makes the output longer|An edit should serve the reader and task, not add complexity for its own sake.`,
`A visual brief says only 'make a picture.' What is missing?|A team asks for an image but gives no audience or purpose. What should be added?|Audience, goal, format and limits|Only a brighter color|Only a file name|A brief sets the job the asset must do, not just how it looks.
An image uses a person's face without permission. What should you check?|A promo mockup includes a real employee's likeness. What comes first?|Consent and permitted use|Whether the image looks realistic|Whether the file is small|A convincing image does not establish permission to use a person's likeness.
AI creates a poster with the wrong date. What review catches this?|A generated event image has clear art but incorrect text. What must be checked?|Every word, number and required detail|Color balance only|Image sharpness only|Generated visuals can contain factual and text errors. Inspect the complete asset.
What helps someone who cannot see an image?|A course diagram carries important information. What should accompany it?|A useful text description|A file name only|A decorative border|A text alternative communicates the important meaning, not every decorative detail.
A training audio clip has no transcript. What is missing?|A learner cannot hear a narrated example. What should you provide?|A transcript or equivalent text|Louder music|A shorter title|Equivalent text makes the lesson available without relying only on sound.
An AI image resembles a protected brand mascot. What should happen?|A design includes a famous logo the team has no right to use. What is safer?|Replace it with approved original material|Use it because AI made it|Hide the logo in a corner|AI generation does not automatically give rights to all elements in the result.
Which file format should be chosen?|You need a visual for a small mobile screen. What should guide export settings?|Where and how the asset will be used|The largest file possible|The creator's favorite format only|Output settings should fit delivery needs, clarity and accessibility.
When should AI use be disclosed?|A company policy requires disclosure on synthetic media. What should the creator do?|Follow the policy and label the asset clearly|Assume viewers will notice|Disclose only if someone complains|Disclosure should follow the relevant policy and avoid misleading viewers.
Your image tool is unavailable. How can you still practice the skill?|A learner cannot access a paid media tool. What is a fair alternative?|Use an approved sample and annotate improvements against the brief|Skip all quality checks|Buy a tool without approval|The learning goal is planning and checking an asset, not access to a specific paid product.
What makes evidence of a media task useful?|An instructor wants to assess the student's design process. What should be submitted?|The brief, output and documented checks|Only the app's home screen|Only the tool name|The brief and review record show whether the output meets the intended need.`,
`AI names a study but supplies no working source. What next?|A market report cites a document you cannot locate. What should you do?|Find and inspect a real source before using the claim|Keep the citation because it looks formal|Ask AI to make the citation longer|A citation-shaped string is not evidence until the source is verified.
Which source best supports a company's current refund policy?|You need the exact current terms for a service. Where should you start?|The official policy page|An old social post|A general AI answer|The organization that owns the policy is the primary source; check its date and scope.
Two sources give different numbers. What should you compare?|Reports disagree about market size. What details may explain the gap?|Dates, definitions, methods and scope|Their colors and layouts|Their word counts|Sources may measure different things or periods. Compare like with like before choosing.
What is a useful research question?|A manager asks 'research AI.' How can you narrow it?|Name the decision, scope and information needed|Collect as many links as possible|Ask for a very long report|A bounded question keeps research relevant to a real decision.
What belongs in a claim/evidence table?|You need to show why a recommendation is credible. What should be recorded?|Claim, source, supporting detail and limits|Claim and confidence only|Source titles without claims|Evidence should be traceable to the specific claim and include important limits.
A source is five years old. Is it automatically useless?|You find an older report while researching a changing product. How should you treat it?|Check whether its facts still fit the question|Reject every older source|Treat it as current without checking|Age matters differently by topic. Current product details need current verification.
What is the difference between a source fact and an inference?|You predict a busy season from two reports. How should you label that conclusion?|An inference based on the reports|A direct quote from both reports|A proven fact with no uncertainty|An inference is your reasoning from evidence, not a statement the sources necessarily made.
AI quotes words that are not on the page. What should you do?|A research draft uses quotation marks around a paraphrase. What is needed?|Remove the false quote and accurately cite or paraphrase|Keep the marks to look credible|Change the author name|Direct quotations must match the source. Paraphrases must preserve meaning and be attributed.
What should a researcher do when evidence is weak?|A recommendation depends on one small survey. What should the report say?|State the limit and what else should be checked|Hide the sample size|Use a more certain tone|Honest limits help decision-makers judge how much weight to place on a conclusion.
Which link belongs with a factual claim?|You cite a specific policy clause. What is the most useful destination?|The page or document that supports the claim|A search results page|The tool's marketing page|Readers should be able to reach the supporting evidence directly.`,
`A sales table mixes dates such as 04/05 and May 4. What comes first?|You are about to chart records with unclear date formats. What should you do?|Standardize and verify the dates|Chart them immediately|Delete every unusual row|Clean, unambiguous data is needed before a calculation or chart can be trusted.
A total includes the same order twice. What is the likely problem?|Two identical order IDs appear in a monthly report. What should be checked?|Duplicate records|The chart color|The column width|Duplicate records can inflate totals. Verify before removing a row because repeated values may sometimes be valid.
A cell is blank. Should you always treat it as zero?|Missing survey responses appear in a dataset. What is safer?|Find out what missing means before calculating|Replace every blank with zero|Ignore missing values without noting them|Missing and zero are different. The choice affects totals and averages.
You have sales of 10, 20 and 30. What is the average?|Three daily counts are 8, 20 and 32. What is their mean?|20|30|60|Add the values and divide by their count. Both examples total 60 across three observations.
Which chart is useful for a trend over time?|You need to show weekly sales changes. Which chart is a good first choice?|A line chart|A pie chart for every week|A decorative word cloud|A line chart can show change over an ordered time axis.
Which chart helps compare categories?|A manager wants to compare sales by department. What usually fits?|A bar chart|An unlabeled image|A line joining unrelated categories|Bars make category values easy to compare. Label units and use a fair scale.
AI writes a spreadsheet formula. What should you do before relying on it?|A generated formula will be copied across a report. What is the best check?|Test known examples and inspect referenced cells|Trust it because it runs|Only check that it is short|A formula can run and still refer to the wrong range or handle blanks incorrectly.
A chart's vertical axis starts at 99 and exaggerates a small change. What should you review?|A presentation makes a tiny increase look huge. Which design choice may mislead?|The axis scale and context|The file name|The title's font only|Scale choices can exaggerate differences. Use a fair presentation and explain the context.
Sales rise after training. Does that prove training caused the rise?|A new tool and higher revenue appear in the same month. What can you conclude?|There is a pattern, but other causes must be checked|The tool caused all the increase|The pattern must be meaningless|A relationship does not by itself prove cause. Other changes may explain the result.
Who should approve a decision based on AI-assisted analysis?|A model recommends a major stock purchase from a small dataset. What is needed?|A person reviews the evidence, limits and business context|Automatic approval from the model|A prettier chart only|A business decision needs judgment beyond the calculation, especially when data is limited.`,
`A meeting agenda lists topics but no purpose. What should be added?|A team keeps meeting without decisions. What should the next agenda state?|The intended outcome for each topic|More attendees by default|A longer meeting time only|An outcome-focused agenda makes preparation and decisions clearer.
AI meeting notes turn a suggestion into an approved decision. What should happen?|A summary says a budget was approved, but the transcript only proposed it. What is wrong?|The notes changed the decision status|The notes are too short|The meeting had too many people|Notes must separate suggestions, decisions and actions. Verify against the source.
What makes an action item complete?|A task says 'contact supplier' but gives no owner or date. What should be added?|Owner and due date|Only a color label|An AI-generated priority with no review|An action needs an accountable person and timing so it can be followed through.
Two people have the same first name in the notes. What should you do?|AI assigns a task to 'Sam' but two Sams attended. What is safest?|Confirm the intended owner|Pick the first Sam in the list|Remove the task|Unclear ownership should be resolved, not guessed.
What should happen before recording a meeting?|A tool offers to record a client call. What must the organizer check?|Consent and the organization's recording rules|Only available disk space|Whether AI can transcribe accents|Recording can capture private information. Follow the applicable consent and handling process.
A summary misses a disagreement. Why does it matter?|AI reports a unanimous decision, but one member raised a major risk. What should be kept?|The relevant concern and actual decision|Only the most positive comments|Only the final sentence|Important concerns and unresolved points affect follow-up and should not be erased.
Which part of meeting notes should be checked against the transcript?|A generated action log includes names and dates. What deserves verification?|Decisions, owners, dates and commitments|Only the greeting|Only the total word count|Errors in these details can send work to the wrong person or create false commitments.
What belongs in a follow-up message?|A meeting has ended with agreed tasks. What should participants receive?|Decisions, actions, owners and dates|The entire raw transcript by default|A generic thank-you only|A concise action-focused follow-up helps people carry out what was agreed.
A tool schedules follow-ups automatically. What safeguard matters?|An agent can invite external guests based on meeting notes. What should happen first?|Review recipients and details before sending|Send first and apologize later|Let the model choose all recipients|Scheduling affects real people. Verify names, access and commitments before acting.
How should unresolved questions be handled?|A meeting ends without a price decision. What should the notes show?|The open question and who will resolve it|An invented price|A claim that everything is settled|Making uncertainty visible prevents a draft from turning into a false decision.`,
`A team wants AI but has not named a problem. What comes first?|A manager asks to automate something because competitors do. What should you clarify?|The workflow problem and desired result|The most expensive tool|A company-wide launch date|Start from a real problem. A tool is useful only if it improves the work.
What is a baseline?|Before a pilot, a team measures time and errors in the current process. What is this?|The starting measure for comparison|The final target|The tool's advertised performance|A baseline shows how work performs before a change, so results can be compared fairly.
A pilot saves 10 hours at $20 per hour and costs $80. What is the net benefit?|A small trial creates $200 of measured value with $80 in costs. What remains?|$120|$200|$280|Net benefit subtracts costs from measured benefits: 200 minus 80 equals 120.
Which cost is easy to miss in an AI pilot?|A budget includes subscriptions but no staff effort. What should be added?|Setup, training and review time|Only the tool's logo design|The number of generated words|People still spend time setting up, learning and checking the new workflow.
What makes a pilot safer?|A team is unsure whether an AI process works. How should it start?|A small reversible trial with clear success and stop rules|A full rollout before testing|No human review until the end|A limited pilot makes mistakes easier to detect and recover from.
What should a success measure describe?|A pilot goal says 'make work better.' How can it improve?|A specific target for quality, time or cost|A vague feeling of progress|Only the number of logins|A measurable goal lets the team judge whether the change actually helped.
The pilot is faster but errors rise. What should the team do?|A tool saves time while sending more incorrect replies. What is the right response?|Compare quality and risk, then adjust or stop|Declare success on speed alone|Hide the errors from the report|Value includes quality and harm, not only speed.
Who should be involved in changing a workflow?|A manager redesigns a process without asking its users. Who is missing?|The people doing and reviewing the work|Only the software vendor|Only the marketing team|People close to the work can identify practical problems, needs and safeguards.
How should estimated savings be presented?|A proposal assumes every saved minute becomes revenue. What should be clarified?|The assumptions and whether savings can actually be realized|Only a larger headline number|A guarantee that the estimate will happen|Saved time may not turn directly into cash. State assumptions and avoid overstating value.
When should a pilot be expanded?|A trial meets its agreed quality and value targets. What comes before wider use?|Review evidence, safeguards and support needs|Remove all checks|Let each person invent a different process|Scaling needs a repeatable process, ownership and ongoing monitoring.`,
`An automated workflow can delete customer files. What should be limited first?|An agent has broad access to records it does not need. What is safer?|Give only the permissions needed for the task|Give full admin access for convenience|Hide the settings from staff|Least-privilege access reduces the damage from mistakes or misuse.
What is a human approval gate?|A workflow drafts refunds but waits for a manager before issuing them. What is that pause?|A required approval before an important action|A model training step|An error that should be removed|Approval gates keep consequential actions under human control.
An agent reads a web page telling it to send private files elsewhere. What should it do?|An external document asks the tool to ignore the user's rules. How should it be treated?|Untrusted content, not an instruction to obey|A higher-priority command|Permission from the document author|External content cannot grant access or replace the authorized task.
What should happen if a tool call fails halfway through?|A workflow updates one record but fails on the next. What is needed?|A clear stop, error log and recovery plan|Repeat every action blindly|Claim the full job succeeded|Partial failure needs a known state and safe recovery to avoid duplicated or lost work.
Why keep an action log?|A manager needs to understand an automated mistake. What helps most?|A record of inputs, actions, results and approvals|Only the final output|Only the agent's name|Logs make actions traceable and support review and recovery.
Which test should a workflow include?|An agent works on perfect input. What else should be tested?|Missing data, bad input and tool failure|Only more perfect examples|Only the welcome screen|Real workflows encounter incomplete input and failures. Test those paths before release.
AI writes code that looks correct. What should happen before running it on important data?|A coding assistant produces a database script. What is the safe next step?|Review and test it in an isolated environment|Run it directly on live records|Assume generated code is safe|Code can make lasting changes. Test and review before giving it real authority.
How can repeated actions cause harm?|A retried payment step sends the same refund twice. What design is needed?|A way to recognize and avoid duplicate actions|A longer delay only|A different confirmation color|Retries must be safe. The system needs to know which action has already succeeded.
When should automation stop and ask a person?|An agent encounters a case outside its approved rules. What should it do?|Pause and request review|Invent new permission|Keep trying unrelated actions|A clear boundary prevents the workflow from expanding its authority on its own.
What should be ready before launch?|An automated process passes a happy-path test. What else is required?|Ownership, monitoring, stop controls and recovery steps|A launch banner only|A promise that no failures will occur|Operations need a responsible owner and a practical way to detect and handle trouble.`,
`A colleague wants to start with AI. What is a sound first step?|A new department asks for an AI trial. What should the team choose first?|A clear low-risk task with safe input|A tool before knowing the task|A live high-impact decision|The course starts from a useful bounded task, then chooses tools and checks.
What should you do with a polished but unsupported answer?|A final project report has convincing claims with no evidence. What needs fixing?|Verify or remove the claims|Improve its visual theme only|Accept the confidence as proof|Quality includes traceable evidence, not just fluent presentation.
Which sequence fits a safe AI-assisted task?|A student is planning their final workplace example. Which order works?|Prepare input, draft, check, approve|Publish, check, then gather input|Choose a tool and skip the review|Safe use combines good inputs with human review before real use.
Which record belongs in a useful prompt portfolio?|An instructor wants to see the student's improvement process. What should be included?|Prompt, input, output, checks and revisions|Only the final answer|Only screenshots of tool menus|The record should show how the work was produced and checked.
How should you explain a tool choice in a capstone?|A project uses a popular product without a reason. What should be added?|Evidence that it fits the task, data rules and cost|A claim that everyone uses it|Only a list of its features|A tool choice should follow the project's requirements and test evidence.
A project result is partly successful. How should it be reported?|A pilot meets the time target but misses the quality target. What is honest?|State both results, limits and next steps|Show only the positive number|Call it a full success|Useful reports describe what worked and what still needs improvement.
Where should private source data go in a student submission?|A learner wants to prove a result using real client records. What is safer?|Use approved redacted evidence or fictional examples|Upload all records for credibility|Hide names but keep account numbers|Evidence must respect data permissions. Removing names alone may not remove identifying details.
What makes a glossary useful?|A beginner forgets what 'retrieval' means. What should a reference provide?|A plain definition and a small example|Only a technical acronym|A long unexplained formula|A concise definition plus an example helps students apply the term.
How should you prepare after a weak practice-check result?|A student misses questions about evidence checking. What should they do?|Review that topic, practice it and retake the check|Memorize letter positions only|Skip the weak topic|Practice checks identify gaps. Use them to improve the skill, not only the score.
What should happen after an AI-assisted project is submitted?|A team adopts a student's workflow. What should remain in place?|A responsible owner, review process and improvement plan|No further checks|Unlimited tool access for everyone|Responsible use continues after the first success through ownership and monitoring.`
];

export function moduleQuestions(index, graded=false){
 return cases[index].split('\n').map((row,i)=>{const [practice,exam,answer,b,c,explanation]=row.split('|');const options=[answer,b,c];const n=(index+i)%3;return {id:`module-${String(index+1).padStart(2,'0')}-${graded?'exam':'practice'}-${i+1}`,question:graded?exam:practice,answer,options:[...options.slice(n),...options.slice(0,n)],explanation};});
}
