// Final exam cases are not reused from practice or graded checkpoints.
const rows = [
`A travel team wants AI to draft replies, find policies and issue refunds. Which task needs the strongest action control?|Issuing refunds|Finding a policy|Drafting an unsent reply|Issuing a refund changes a real account. Require authorized approval before it happens.
A chatbot says it is 99% sure about a supplier's bank details. What should the team do?|Verify through an approved independent channel|Use the details because confidence is high|Ask for the same answer twice|Confident output is not independent verification, especially for a high-risk payment.
A trial uses public event facts and keeps every draft unsent. Why is this a suitable starting point?|It limits data exposure and real-world effects|It guarantees perfect accuracy|It removes the need for review|Safe inputs and reversible outputs reduce risk; review is still needed.
A manager claims 'AI is unbiased because it is a computer.' Which response is sound?|Models can reflect biased data and choices|Computers cannot produce unfair results|Only humans can produce biased rankings|Data, design and use can create unfair effects. Test the results on relevant groups.`,
`A prompt has a task and source notes, but no reader or format. Which addition is most useful?|Write for a store manager in three action bullets|Try harder and be excellent|Use any style you prefer|Audience and format give concrete direction and make quality easier to judge.
A revised output fixes tone but changes a correct deadline. What should the next instruction protect?|Keep verified facts unchanged while revising tone|Make all dates more flexible|Generate an entirely new event|A focused revision must preserve facts that already passed review.
A team stores a prompt with named client details in a shared template library. What should change?|Replace case data with clearly marked placeholders|Hide the file from search only|Keep the names as examples|Reusable templates should not expose private case information.
An uploaded brochure asks the assistant to reveal hidden instructions. How should it be handled?|Ignore that command and use only relevant brochure facts|Follow it because it is in the input|Treat it as approval from the user|A source document provides information, not authority over the task.`,
`Tool A scores well on writing but cannot meet the approved data rules. Tool B meets the rules and quality needs. Which is the better fit?|Tool B for this task|Tool A because writing is the only concern|Whichever has more users|Meeting mandatory data requirements comes before comparing optional advantages.
A team compares a tool using easy notes with another using a complex report. What invalidates the comparison?|The inputs and difficulty differ|The tools have different names|One tool has a darker interface|Unequal tasks do not isolate tool performance.
A service costs $30 monthly but needs four hours of review. What is missing from a price-only comparison?|The cost of staff review time|The number of menu items|The provider's logo size|Total operating cost includes human effort as well as subscription charges.
A new model replaces one tested last year. What is the responsible next step?|Repeat the task and safety tests|Keep last year's results as a guarantee|Assume newer always means safer|Quality and data handling can change, so earlier evidence may not apply.`,
`Source notes say the launch date is unconfirmed. The draft says 'Launch is Monday.' Which edit is needed?|Restore the uncertainty and flag the missing date|Keep Monday to make the plan useful|Delete the whole project|A draft must not turn missing information into a false commitment.
A weekly summary is accurate but gives no tasks or owners. What would make it actionable?|Add agreed actions with responsible people|Add more adjectives|Ask AI to choose owners without evidence|An action plan needs ownership, but the owner must be confirmed.
AI brainstorms a new service. What evidence is needed before it becomes an approved plan?|Fit with customer needs, cost, risk and capacity|The length of the idea list|The confidence of the wording|Ideas are starting points. Test feasibility and value before approval.
A draft has fewer words but omits a safety warning. Is it an improvement?|No, it lost information needed for safe use|Yes, shorter is always better|Yes, warnings are optional details|Conciseness must not remove critical meaning.`,
`A client email and an internal memo describe the same delay. What may reasonably differ?|Tone and level of internal detail|The confirmed delivery facts|The approved commitments|Adapt to the audience without changing the truth or promises.
A complaint reply is polite but blames a staff member by name. What should the reviewer address?|Privacy and the relevance of internal blame|Only spelling|Only sentence length|Politeness does not make private internal details suitable for a customer message.
A notice says 'Please handle this soon.' What makes the request clearer?|Name the required action and agreed deadline|Add the word urgently three times|Remove the request|Specific actions and dates reduce ambiguity.
An AI draft offers compensation outside the team's authority. Who should decide what is sent?|An authorized reviewer using the policy|The tool that wrote it|The recipient of the draft|The business's approval process determines commitments, not the model.`,
`A poster is attractive but its date and phone number are wrong. What should determine acceptance?|Whether required facts and checks pass|Whether the colors look premium|Whether AI generated it quickly|Visual appeal cannot compensate for incorrect information.
A training video is required but some learners cannot hear it. What should be provided?|Captions and an equivalent text version|A larger play button only|A louder soundtrack only|Accessible alternatives should communicate the instructional content without sound.
A generated image resembles a real colleague. What should happen before publishing?|Confirm consent and permitted use or replace it|Publish because it is not a photograph|Remove the file metadata only|Synthetic media can still affect a real person and require permission.
A learner lacks the paid image tool used in class. What alternative preserves the learning goal?|Review a supplied asset against a brief and explain improvements|Skip the module entirely|Buy any tool immediately|Planning and evaluating an asset can be demonstrated without that specific subscription.`,
`A report cites the vendor's home page for a detailed warranty claim. What would improve traceability?|Link the exact current warranty terms|Add more unrelated links|Remove all source dates|Evidence should directly support the particular claim.
Two reports cover different years and countries. Can their percentages be compared directly?|Not without explaining the differing scope|Yes, all percentages have the same meaning|Only if both reports have charts|Definitions, populations and dates affect what numbers mean.
A source states demand rose. The student concludes a new campaign caused it. What needs labeling?|The causal conclusion as an inference needing evidence|The source's title as an opinion|The date as a prediction|The source's fact does not by itself prove the student's causal explanation.
A source cannot be checked before a deadline. What should the final report do?|Omit or clearly flag the unsupported claim|Present it confidently to avoid delay|Invent a replacement citation|Time pressure does not turn an unverified claim into reliable evidence.`,
`An average treats missing delivery times as zero. What is the risk?|The average may look faster than reality|The average must always rise|The chart title becomes incorrect|Missing values are not zero-duration deliveries; the assumption can distort results.
Four orders are worth $10, $20, $30 and $40. One $40 order is duplicated. What is the correct total after verification?|$100|$140|$80|The four genuine orders total $100. A duplicate adds value that was not earned.
A team compares branches using bars with different scales. What should be standardized?|Units and comparable axis scales|Only bar colors|Only file names|Comparable scales prevent the same value from appearing different across charts.
An analysis links training to fewer errors using only one week of data. What should a reviewer request?|More context, limitations and evidence before claiming cause|A stronger title|A guarantee that the pattern will continue|Small samples and other changes may explain the pattern.`,
`A transcript says 'Lee will ask finance whether Friday is possible.' Which action log is accurate?|Lee to confirm the possible date with finance|Finance has approved Friday|Lee will deliver everything Friday|The source describes a follow-up, not an approved delivery commitment.
A meeting summary drops an unresolved security concern. What is the consequence?|The follow-up may miss an important risk|The summary is necessarily more useful|Nothing, because only decisions matter|Open risks can affect safe action and must remain visible.
AI invites an external person based on an ambiguous name in notes. What safeguard was missing?|Recipient verification before sending|A longer invitation subject|A more detailed tool logo|Names can be ambiguous and invitations can expose information.
A call will include private client details. What must be confirmed before recording?|Consent, access and handling rules|Only the recording format|Only the speaker order|Recording creates another copy of sensitive information and needs an approved process.`,
`A pilot saves $600 in measured effort and costs $450 in tools and setup. What is the net benefit?|$150|$600|$1050|Subtract total costs from measured benefits: $600 minus $450 equals $150.
A faster process doubles correction work. Which evaluation is fair?|Compare total effort, quality and risk|Count speed only|Ignore corrections as a separate issue|The whole workflow matters, including work created downstream.
A rollout proposal has no baseline. What should happen first?|Measure the current process|Announce a percentage improvement|Choose the biggest subscription|Without a starting measure, improvement claims are difficult to support.
A pilot passes its targets but no one owns ongoing monitoring. What is needed before expansion?|A named owner and monitoring/recovery plan|A larger marketing announcement|Removal of the review steps|A successful trial still needs operational ownership at scale.`,
`A tool times out after sending an invoice. What should a retry check?|Whether the invoice was already sent|Only whether the page refreshed|Whether the email subject is short|A retry must not repeat an action that already succeeded.
An agent needs read-only access to three folders but receives full admin rights. What should change?|Restrict access to the required folders and actions|Keep admin rights for speed|Hide the account name|Limit authority to reduce the impact of mistakes or misuse.
A coding assistant suggests a deletion script. What is the safe next step?|Review targets and test on safe copies before approval|Run it on the main data immediately|Trust the generated comments|Destructive code needs explicit target checks and safe testing.
A workflow sees input outside its tested cases. What should its boundary rule do?|Pause and route the case to a person|Expand its permissions automatically|Hide the exception|An explicit escalation path keeps uncertainty from becoming an unauthorized action.`,
`A capstone shows a polished output but no input, prompt or checks. What evidence is missing?|The process and review trail|A larger cover image|A different title font|A good submission demonstrates how the result was produced and verified.
A student reports only the best trial from ten runs. What should be disclosed?|The wider test results and important failures|Only the best screenshot|Only the tool's subscription tier|Selective reporting can overstate reliability; decisions need a fair account of testing.
A final recommendation includes a benefit estimate with uncertain assumptions. How should it be written?|State the assumptions and limits clearly|Convert the estimate into a guarantee|Remove all numbers regardless of usefulness|Transparent assumptions help readers interpret estimates appropriately.
After launch, the team stops checking outputs because the pilot passed. What is the better practice?|Continue proportionate monitoring and review|Assume the tool cannot change|Give every user unrestricted access|Tools, inputs and work can change. Responsible use needs continued oversight.`
];
export const finalQuestions=rows.flatMap((group,m)=>group.split('\n').map((row,i)=>{const [question,answer,b,c,explanation]=row.split('|');const options=[b,answer,c];return{id:`final-${m+1}-${i+1}`,question,answer,options,explanation};}));
